language: node_js
node_js: stable
root: linux

env:
  global:
    - secure: 

addons:
  apt:
    update: true

cache:
  directories: 
    - node_modules

branches:
  only:
    - master

before_install:
  - npm install -g gitbook-cli

install:
  - npm install
  - gitbook install

script:
  - gitbook build

deploy:
  provider: pages
  email: shepherd@orkva.com
  token: $GH_TOKEN
  cleanup: true
  keep_history: true
  local_dir: _book
  on:
    branch: master
